spring.application.name=matching-core
nats.url=nats://localhost:4222
matching.disruptor.ring-buffer-size=1024

chronicle.data-dir=./data
chronicle.map-max-entries=1000
chronicle.map-average-key-size=10
chronicle.map-average-value-size=4096

charts.timeframes=1m,5m,15m,1h,4h,1d
charts.max-candles-per-series=1000
