spring.application.name=matching-core
nats.url=nats://localhost:4222
matching.disruptor.ring-buffer-size=1024

chronicle.data-dir=./data
chronicle.map-max-entries=1000
chronicle.map-average-key-size=10
chronicle.map-average-value-size=4096
