spring.application.name=trading-api

spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=http://localhost:8081/oauth2/introspect
spring.security.oauth2.resourceserver.opaquetoken.client-id=test-client
spring.security.oauth2.resourceserver.opaquetoken.client-secret=test-secret
